### ISSUE TITLE
Error: not found()

### ISSUE THREAD

**Issue by noamross** [MilesMcBain/gistfo#1]
Hi, first time user here!  I have a pretty non-informative error when I try to use this.  The error pops up in a window when activating the add-in but when I use the function at the console, I get:

```
> gistfo::gistfo()
Error: Not Found
> gistfo::gistfoc()
Error: Not Found
> traceback()
7: stop(res$message, "\n", errs, call. = FALSE)
6: stopstatus(x)
5: process(response)
4: gist_POST(paste0(ghbase(), "/gists"), gist_auth(), ghead(), body, 
       ...)
3: gistr::gist_create(filename = gist_name, public = public, browse = browse, 
       code = source_context$contents)
2: gistfo_base(mode = "carbon")
1: gistfo::gistfoc()
```

**Comment by MilesMcBain** [comment]
Eeep this looks like it is bubbling up from `gistr`. Did it create a gist at all?

**Comment by MilesMcBain** [comment]
Question 2: Are you in an RStudio project or file with any special characters in the name?

**Comment by noamross** [comment]
No, I am not.  I was in a project with a-z letters only, and then again in no project at all.  Same error in both cases.

**Comment by noamross** [comment]
No, it did not create a gist. Pinging @sckott.  I definitely have a working `GITHUB_PAT` in the environment.

**Comment by noamross** [comment]
![carbon](https://user-images.githubusercontent.com/571752/36851380-1700bbb2-1d37-11e8-92c4-860ee1b48fab.png)

**Comment by sckott** [comment]
hugh - seems like we need better error message here from github- either they do give a good message, and I just don't pass it on, or they don't and we're shi* out of luck - can look int oit

**Comment by noamross** [comment]
I think they give "404 Not found" whenever you try to access something that
you don't have credentials for.  Which is probably the most secure way to
do it, as they don't want to give away that somethings exists if it is
private.

**Comment by sckott** [comment]
yes, true, 404 for both actually doesn't exist and you just don't have creds

i still want to look to see if there is any other error message stuff I'm not passing on, probably there won't be

**Comment by sckott** [comment]
looking at this

**Comment by sckott** [comment]
@noamross @MilesMcBain don't know if you have interest/time to test, but if you do, i improved error message by inspecting response headers. e.g., 

```r
gist_create(files=file, description='a new cool gist')

#> Error: Not Found
#> 
#>   GitHub response headers suggest no or insufficient scopes
#>   To create gists you need the `gist` OAuth scope on your token.
```
