### ISSUE TITLE
Fetching Gists

### ISSUE THREAD

**Issue by MilesMcBain** [MilesMcBain/gistfo#5]
It would be nice to grab a gist and insert it into the active source tab or clipboard.

There's some thinking to do about the interface that goes along with this: exploring your gists, filtering etc.

**Comment by MilesMcBain** [comment]
Waaaaaaaaaa It's happening!

**Comment by gadenbuie** [comment]
Now possible with `gistfo_app()` or the **Gistfo App** addin! #11
